{{- if and .Values.components.auth (not .Values.authSession.sentinel.addresses) }}
# SPDX-License-Identifier: AGPL-3.0-only
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-sessions-state
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: sessions-state
    platform.scitrera.io/trust: service
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storage.className | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}

{{- end }}
