# SPDX-License-Identifier: AGPL-3.0-only
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-runtime
  annotations:
{{ toYaml .Values.serviceAccountAnnotations | indent 4 }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: runtime
    platform.scitrera.io/trust: service
automountServiceAccountToken: false
