# SPDX-License-Identifier: AGPL-3.0-only
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-aether-state
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: aether-state
    platform.scitrera.io/trust: service
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storage.className | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
{{- if ge (int .Values.phase) 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-provider-state
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: provider-state
    platform.scitrera.io/trust: service
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storage.className | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}

{{- end }}

{{- if ge (int .Values.phase) 2 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-memorylayer-data
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storage.className | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
{{- end }}
