apiVersion: v2
name: platform-shared
version: 0.1.0
type: application
description: Scitrera shared integration release
appVersion: candidate-2026-09-11
kubeVersion: '>=1.34.0-0 <1.35.0-0'
dependencies: []
